name        = "Huguette"
license     = "MIT"
licenselink = ""
description = "A very minimal theme for Hugo with options for classless.css and NetlifyCMS"
homepage    = ""
demosite    = ""
tags        = ["clean", "minimal", "simple", "classlesscss", "netlifycms", "light", "resposive"]
features    = ["classlesscss", "NetlifyCMS", "lightweight", "resposive"]

[author]
  name      = "Cathelijne Hornstra"
  homepage  = ""
  